### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by JasimAlrawie** [spckio/spck-issues#105]
console.log doesn't work🤔
sometimes!!!
[Look here](http://imgur.com/a/Mz5ip9e) 
version: 4.0.1

**Comment by spck-io** [comment]
I’m aware of this issue. The problem is eruda console is loaded after the web application. So console log will only work after everything is loaded. I need to figure how to fix this for eruda console or default back to the old console and lose a lot of great features, such as better stack traces for errors...

**Comment by JasimAlrawie** [comment]
> I’m aware of this issue. The problem is eruda console is loaded after the web application. So console log will only work after everything is loaded. I need to figure how to fix this for eruda console or default back to the old console and lose a lot of great features, such as better stack traces for errors...

yeah i did consoleLog in click event and it worked 🤔
maybe if i use defer on the script tag maybe this would fix this problem🙂

**Comment by JasimAlrawie** [comment]
naah  defer did nothing 😅

**Comment by spck-io** [comment]
Update 4.1.0 should fix this. Let me know if this is still an issue after the update.

**Comment by JasimAlrawie** [comment]
working perfectly thanks for your hard work🙂
