### ISSUE TITLE
Physical keyboard support

### ISSUE THREAD

**Issue by EdgeMcQueen** [spckio/spck-issues#158]
Hello, thanks for the great code editor!  but I ran into one issue.  If you connect a physical keyboard to a smartphone, then using the application becomes impossible.  After each keystroke, the cursor disappears from the editor area and offers snippets. Is it possible to make async snippets popup and code input? Thank You!:)

**Comment by abolfazleslami1990** [comment]
Yeah it is interesting

**Comment by spck-io** [comment]
Do you have a video that can help with debugging this? I do not have the ability to test physical keyboards attached to smart phone. Thanks.

**Comment by EdgeMcQueen** [comment]
> Do you have a video that can help with debugging this? I do not have the ability to test physical keyboards attached to smart phone. Thanks.


https://youtu.be/VzGH71xqq4s

**Comment by nathaneltitane** [comment]
In this matter @spck-io I would like to suggest a more granular set of features for widgets, completion and snippets that we can enable/disable depending on whether or not a physical keyboard is connected to the device (usb or bluetooth)

I am in a similar position where using my Note10+ with Dex and having a bluetooth keyboard connected makes for a sub-par desktop-like experience on the deitor given the continued interruptions due to popups

**Comment by EdgeMcQueen** [comment]
> In this matter @spck-io I would like to suggest a more granular set of features for widgets, completion and snippets that we can enable/disable depending on whether or not a physical keyboard is connected to the device (usb or bluetooth)
> 
> I am in a similar position where using my Note10+ with Dex and having a bluetooth keyboard connected makes for a sub-par desktop-like experience on the deitor given the continued interruptions due to popups

When I use DeX with a connection to a laptop, all the functions work properly.  But in this case, the meaning of using a mobile IDE disappears :)

**Comment by spck-io** [comment]
Using GBoard as the default keyboard solves a lot of issues for other users.

**Comment by nathaneltitane** [comment]
what about physical keyboards? there is a use case for external monitors and desktop-like experience as well...

**Comment by spck-io** [comment]
The Soft Keyboard has an effect on the IME of physical keyboards. There is a new setting "Soft Keyboards" that allow turning off the Virtual Keyboard while when a Physical Keyboard is detected, but I believe the choice of the Virtual Keyboard (GBoard, SwiftKey) still impacts how the keyboard interacts with the app. Since the app runs in a Webview, there are some edge-case bugs not considered by keyboard implementations that are not present on GBoard.
