### ISSUE TITLE
Can't push to Github

### ISSUE THREAD

**Issue by Mesteery** [spckio/spck-issues#171]
Hello, i am using the last version of spck editor

When i push to Github it say `Successfuly pushed to remote [origin]` but it doesn't really push.

And in the Github there is no new commit :/

**Comment by cdurau** [comment]
Same here. Tried with password and token.

Galaxy Tab S4, Android 10.

Solved it:
The problem was with github, not the editor. My email was set to private and github didn't allow to push changes which would display the email in the meta data. 

If you got the same error try:
- Go to settings
- Emails
- uncheck "Block command line pushes that expose my email"

Have a nice day! =)

**Comment by WhittlesJr** [comment]
I'm having this issue as of today. I don't see any such settings as @cdurau suggested in my GH settings. This was working a week or so ago...

**Comment by WhittlesJr** [comment]
I found that it was a GitHub issue as well for me. My access token didn't allow workflow changes, and I had changes that affected workflow. Adding workflow permissions to the access token fixed that.

You'd think that spck should be able to report that the push failed though...
