### ISSUE TITLE
Add push "force" option

### ISSUE THREAD

**Issue by Mesteery** [spckio/spck-issues#173]
Hey, can you add a option to force push ?

**Comment by Mesteery** [comment]
(and pull)

**Comment by spck-io** [comment]
Force push is on the roadmap, but I want to get the git features more stable before doing something risky. Additionally, repos that are shallow cloned cannot use force push as that would delete the repo history. (Support for deep cloning has only been added in 5.0)

**Comment by aisbergde** [comment]
why this issue is closed? I can't find a way to force a push. And now I can't push my changes anymore, because I get the error that I need a force push. How I can solve the issue? If I can't push my changes then I can't use the editor with this repository. For me this is a fatal issue because I have no idea how to solve it. Is there any idea how to get the editor to work again? And how to avoid these situations?

**Comment by SpellboundScents** [comment]
This is still an issue, could we get a force option, or at least an in-app terminal to send git commands?
