### ISSUE TITLE
Java invocation error on github clone

### ISSUE THREAD

**Issue by nathaneltitane** [spckio/spck-issues#176]
Attempting to clone another of my repositories and it fails prompting me with this message:

![Screenshot_20200609-130618_Spck Editor](https://user-images.githubusercontent.com/5674757/84178293-2996a480-aa52-11ea-88b7-c44d4023d587.jpg)

UPDATE:

This seems to be due to mishandling, or not handling at all files of large size - I had to remove a subdirectory containing deb files for the repo to sync.

**Comment by spck-io** [comment]
This is a limitation of the app. The editor is written in a way where the use of Java file streams is not possible due to limitations of how JavaScript interacts with Java code. If you have any suggestions on how streaming writes is possible between JavaScript / Java bridge I would be interested in a solution as well.
