### ISSUE TITLE
Open project from directory option missing

### ISSUE THREAD

**Issue by lethevimlet** [spckio/spck-issues#27]
Cloning form GitHub is very nice, or importing a zip file, but a plain open project from directory option, is mandatory in my opinion.

**Comment by spck-io** [comment]
The android filesystem is very hard to use for this purpose. I will do more research on this, but the whole Android filesystem seems designed for social media apps or media related apps. I don’t think making it easy to open directories was a top concern for the Android team.

**Comment by spck-io** [comment]
This will probably never be supported since android 7+ prevents apps from getting the path of files due to security concerns. This makes it impossible to guess the layout of the directory without significant overhead. If google decides to implement a better way in future versions of android, for example a scoping mechanism to prevent access outside the scoped folder while still allowing apps to access the folder in the same way, I would jump on supporting this right away. Right now using content resolver just reading the file name is an absurdly complicated process.
