### ISSUE TITLE
Suggestion: List of keyboard shortcuts

### ISSUE THREAD

**Issue by jepsuCoded** [spckio/spck-issues#36]
Hi good day! Is it possible to put a list of all keyboard shortcuts available for this app since its quite confusing at first such as CTRL-D duplicates the line whereas CTRL-Y deletes the line. Its such a small thing to ask but a big help for us mobile users to know what shortcuts to use to save time manually doing things inside the editor thank you for this awesome app!

**Comment by benhormann** [comment]
Here are some Spck shortcuts:

Windows | Mac | Action
---- | ---- | ----
Ctrl-B | Cmd-B | Go to Definition
Ctrl-I | Cmd-I | Get Info
Ctrl-P | Cmd-P | Get Signature
Alt-R / F2 | Opt-R / F2 | Rename Symbol
Ctrl-Shft-D / Ctrl-Y | Cmd-Shft-D / Cmd-Y | Remove Line
Ctrl-D | Cmd-D | Copy Lines Down
Ctrl-R | Cmd-Opt-F | Replace
Ctrl-Shft-Up | Cmd-Shift-Up | Move Lines Up
Ctrl-Shft-Down | Cmd-Shift-Down | Move Lines Down
Ctrl-S | Cmd-S | Force Save
Ctrl-Shft-F | Cmd-Shft-F | Find & Replace in Files
Alt-F | Opt-F | Format
Ctrl-G | Cmd-G | Go to Line

There are more for the find / replace dialog:

Windows | Mac | Action
---- | ---- | ----
Esc | Esc | Close search bar
Ctrl-F | Cmd-F | Find mode (focus find input)
Ctrl-R / Ctrl-H | Ctrl-R / Ctrl-H / Cmd-Opt-F | Replace mode (focus replace input)
Ctrl-G | Ctrl-G / Cmd-G | Find next
Ctrl-Shft-G | Ctrl-Shft-G / Cmd-Shft-G | Find previous
Return | Return | Replace and find next
Shft-Return | Shft-Return | Replace and find previous
Alt-Return | Alt-Return | Replace all
Tab | Tab | Switch input field
Alt-R / Alt-/ | Ctrl-Opt-R / Ctrl-Opt-/ | Toggle regex matching
Alt-C / Alt-I | Ctrl-Opt-R / Ctrl-Opt-I | Toggle case sensitive matching*
Alt-B / Alt-W | Ctrl-Opt-B / Ctrl-Opt-W | Toggle whole word matching

\* My guess is that Ctrl+Opt+R is a mistake and it should be Ctrl+Opt+C.

Otherwise you can try the shortcuts listed here: [Ace Wiki - Default Shortcuts](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts)

**Comment by spck-io** [comment]
Thanks for this list. Sorry for the delay but a list of shortcuts can now be found in the settings.

**Comment by ghost** [comment]
clicking on tab making (div) to <div></div> if I use div.not it's not working if I use that build in button (arrow lokking one In a corner)it will work fine
