### ISSUE TITLE
Does not save project. 

### ISSUE THREAD

**Issue by cambo2015** [spckio/spck-issues#37]
I spent a bit in a project, specifically in a blank regular html file with no framework. I thought the auto save feature would work, but when I closed and then reopened the app,  I was supprised to see my project wasnt there😱. The editor is so great though . I use this when I am feeling sick and unable to work. Perhaps a manual save button in case auto save is down?

**Comment by spck-io** [comment]
Hi, really sorry to hear that, being a developer I know how that must feel. I wrote extensive tests for the database storage APIs as your files are stored using IndexedDB technology. But because of constant issues with indexDB, I do plan on rewriting the entire file storage code to enable external storage on Android. However this is no easy task as I now need to support both indexDB and the file system which works in completely different ways. IndexDB May sometimes fail silently for unknown reasons to me and if your Chrome has run out of storage or is exceeding its storage limits or you have cleared all app data for your Chrome. Thank you for kind comments and hopefully I can resolve this for you in the future.
