### ISSUE TITLE
cannot select a class[can't write "." in style]. this bug is only in microsoft swiftkey keyboard... spck v6.0.5

### ISSUE THREAD

**Issue by panchalbhavya2210** [spckio/spck-issues#400]
https://user-images.githubusercontent.com/94476517/147807120-1e3f701b-e9c5-4a86-8936-799196537256.mp4

**Comment by Proxtx** [comment]
this is some sort of autocompletion. Use GBoard

**Comment by gabriel-pipia** [comment]
I have a similar problem I can not understand why he does not write.davise xiaomi redmi note 9s

**Comment by Aplha101** [comment]
> I have a similar problem I can not understand why he does not write.davise xiaomi redmi note 9s
> 
> 

Use Gboard ( as stated by @Proxtx ) I've been using it and didn't get any typing bugs within the editor

**Comment by panchalbhavya2210** [comment]
> > I have a similar problem I can not understand why he does not write.davise xiaomi redmi note 9s
> > 
> > 
> 
> Use Gboard ( as stated by @Proxtx ) I've been using it and didn't get any typing bugs within the editor 

    there is no bug using GBOARD, but suggestions strip in microsoft swiftkey is  better than any keyboard. it helps me write code faster. and this bug is also available in SwiftKey beta. btw i'm using soft keyboard built in spck editor to type "."

**Comment by spck-io** [comment]
I have a new IME mode in the next version that should fix this problem. If you only need Latin keyboard, you can switch the "IME Mode" under "Settings" to Basic which may fix this. Otherwise, if there is some way to turn off conversion of "." to ". " (in SwiftKey) it would also fix this problem. There is a conflict with how GBoard and SwiftKey autocorrects. For example, GBoard converts 2 spaces "  " to ". " which is an annoying problem for some users, and SwiftKey autocorrects "." to ". ". I have tried turning off the AUTOCORRECT flag for the Keyboard, but SwiftKey does not respect this flag.
