### ISSUE TITLE
nos save fills

### ISSUE THREAD

**Issue by fifia07** [spckio/spck-issues#454]
Does not save projects why I could not understand![Screenshot_2022-03-17-21-51-18-754_io.spck.jpg](https://user-images.githubusercontent.com/101568075/158865140-5b00032e-8535-41b9-85c3-4bc384944355.jpg)

**Comment by spck-io** [comment]
Did you open the file from file manager or a different app? (i.e. Messenger?) Can you open the "Log History", found in Settings and paste what is shown there when you have the saving issue? Thanks.

**Comment by aatz1982** [comment]
This same error has happened 5 times in the last week to me and has unfortunately rendered spck editor (android) un-useable unless i want to upload to github every time i write a line, as it blanks the entire file with no way to recover it. By the time i have noticed it mins later whatever it is has fallen off the end of the short log with 50x identical '[update]' logs. so can't really add much more than the above screenshot, other than i looked in android/data/io.spck/... afterward and the file seems to just be gone. It's happened to 2 files, one in each of the projects i have on there. The files were created and opened directly in spck editor.

**Comment by aatz1982** [comment]
only these logs occured during a save-fail
[13:29:21] [update]: ~/WebGLTest/glt.js
[13:29:21] [put]: ~/WebGLTest/glt.css
[13:29:21] [clear]: css
[13:29:21] [clear]: html
[13:29:21] [clear]: javascript
[13:29:21] [save] rename failed: EXDEV (Cross-device link)
[13:29:21] [metadata] clear cache

The file it failed to save is called glt.html
build 6.1.0

**Comment by spck-io** [comment]
Thanks this is very helpful. I have some idea what may be going on, will investigate.

**Comment by spck-io** [comment]
I looked into it and believe this is caused by a cache invalidation issue. Meaning when switching projects stored on different partitions (External vs Internal) it does not switch the tmp directory over to the new partition causing the editor attempting to do a cross-link across different partitions. I have rewritten the caching code to use a simpler model in 6.1.2, please let me know if you experience this issue from this version onward. Additionally I increase the logging around save error events, so if you do encounter this again please include the logs as it would be very helpful.

**Comment by aatz1982** [comment]
Thanks I can confirm that in my case one project is currently stored 'Internal' and the other 'External', I now have update 6.1.2 and will report any further occurence. 

I notice the Internal / External toggle on the Workspace screen tells me 'External (Error 221 GB)', the associated log could be '[00:11:34] [filesystem] unknown drive state: mounted', I hadn't noticed it before as had swiched between them on the 'recent' list, assume it's unrelated anyway
