### ISSUE TITLE
Bug while deleting text

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#515]
I've noticed that sometimes when i hit backspace instead of deleting the text it copy pastes whatever is there in my clipboard
Please try to investigate this 

Version : 6.2.11 ( latest ) 
Keyboard : G board 

Also there are a bit of issues with the "touch hold to select" thingy , It selects things unintentionally when changing lines or just scrolling , maybe increasing the delay can help

**Comment by spck-io** [comment]
I will increase the delay from 500ms to 850ms on the "hold to select" to see if that helps.
 
After some investigation it seems the issue could be coming from the G board.
(See https://www.reddit.com/r/nexus6/comments/50pkod/601_android_keyboard_inserting_words_on_backspace/)

Maybe a restart of your phone could help, or maybe include a video of when it happens and I could try to replicate the actions in the video as close as possible to try and see what's happening.

Edit: Under Settings, what IME Mode are you using? By default it is "Code", there are some issues with Basic IME Mode, but it's there because it works better on older phones (Android 5-6).

**Comment by Aplha101** [comment]
> I will increase the delay from 500ms to 850ms on the "hold to select" to see if that helps.
>  
> After some investigation it seems the issue could be coming from the G board.
> (See https://www.reddit.com/r/nexus6/comments/50pkod/601_android_keyboard_inserting_words_on_backspace/)
> 
> Maybe a restart of your phone could help, or maybe include a video of when it happens and I could try to replicate the actions in the video as close as possible to try and see what's happening.
> 
> Edit: Under Settings, what IME Mode are you using? By default it is "Code", there are some issues with Basic IME Mode, but it's there because it works better on older phones (Android 5-6).

My IME mode is Code ( default ) , for the screen recording  the bug is  not that frequent I tried to record but the video stretched to 3mins 

It just happens sometimes and it either copy pastes things on my clipboard or it pastes/duplicates the word that it's deleting

**Comment by Aplha101** [comment]
> > I will increase the delay from 500ms to 850ms on the "hold to select" to see if that helps.
> >  
> > After some investigation it seems the issue could be coming from the G board.
> > (See https://www.reddit.com/r/nexus6/comments/50pkod/601_android_keyboard_inserting_words_on_backspace/)
> > 
> > Maybe a restart of your phone could help, or maybe include a video of when it happens and I could try to replicate the actions in the video as close as possible to try and see what's happening.
> > 
> > Edit: Under Settings, what IME Mode are you using? By default it is "Code", there are some issues with Basic IME Mode, but it's there because it works better on older phones (Android 5-6).
> 
> My IME mode is Code ( default ) , for the screen recording  the bug is  not that frequent I tried to record but the video stretched to 3mins 
> 
> It just happens sometimes and it either copy pastes things on my clipboard or it pastes/duplicates the word that it's deleting 
> 

The bug is similar to Codesnack IDE  but less worse and less often

**Comment by spck-io** [comment]
> I've noticed that sometimes when i hit backspace instead of deleting the text it copy pastes whatever is there in my clipboard Please try to investigate this

Did this start occurring in the latest 6.2.11? Also does it paste whatever is at the current cursor? Or if you copy some random text from 10 minutes ago, it will start pasting the previous copied text? I may have a theory on what's happening if it's pasting/duplicating the current cursor text.

**Comment by Aplha101** [comment]
> > I've noticed that sometimes when i hit backspace instead of deleting the text it copy pastes whatever is there in my clipboard Please try to investigate this
> 
> Did this start occurring in the latest 6.2.11? Also does it paste whatever is at the current cursor? Or if you copy some random text from 10 minutes ago, it will start pasting the previous copied text? I may have a theory on what's happening if it's pasting/duplicating the current cursor text.

Yep its on 6.2.11 and yeah it pastes whatever it's deleting :/

**Comment by spck-io** [comment]
Thank you, that is very helpful information. Here are my thought's, in the recent release, I updated the editor codebase from what I thought were minor fixes in ace editor library. However, the library made some modifications to tokenization (converting text to syntax tokens) and also mouse handling. Normally, you would think these minor modification shouldn't have any impact on text input, but after scanning through the code, these operations "may" infact trigger a text edit "endOperation" which will cause any difference to be updated to the editor. I will revert the updates from ace editor library and see if this fixes your issues. Additionally there may be a race condition when deleting text (deletion triggers the textinput change to from (test -> tes) the editor triggers an endOperation asynchronously due to tokenization or new mouse handling code, then editor does a check and sees (tes != test) and thinks this is a new input (cursor position may also be messed up causing (tes) to be reinserted.

**Comment by spck-io** [comment]
Let me know if this issue is still occurring on latest (6.2.12).

**Comment by Aplha101** [comment]
> Let me know if this issue is still occurring on latest (6.2.12).

I didn't see the bug in these 15days so ig it's gone?if i see it again I'll update here
