### ISSUE TITLE
Short loading times - idea

### ISSUE THREAD

**Issue by Proxtx** [spckio/spck-issues#53]
I know you are using indexed DB and it is loading Files very fast ... But the loading times of the editor are depending of the strength of the internet connection. Maby you are already using this Methode, but I think it would be a good idea to save some files from Spck Editor Web App in the indexedDB and load them at the start from it instead of loading them from the server.

**Comment by spck-io** [comment]
The loading times issue has been solved in the next Android app version. With a fast internet connection, the bulk of the loading time depends on how fast your phone can evaluate JavaScript. The reason why the loading time is bad with an unstable connection is because the service worker first tries to test if it can fetch an update from the server before trying to load it from cache. I have not set a timeout for this process, if you are not connected to any network, this should fail immediately and everything will be loaded directly from the service-worker cache. The new app version has a timeout on this process and in the case where there’s no network or timeout, it will directly fetch from the filesystem cache in the app. This means it doesn’t even need to go through the service worker cache. The service worker in the app is essentially already performing what you’re suggesting but the additional check for updates is what is holding up the loading time.

**Comment by Proxtx** [comment]
When will the next Version be released?
