### ISSUE TITLE
Some issues with the latest update (ver: 7.0.0)

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#559]
1;With the new update the UI got improved , it's alright I'm not a big fan but it's fine but the problem is all my fonts are gone , i used PT mono but now I'm trying to download it and set it as my font but nothing is happening it's just stuck to the default font , I'm not sure if it's just me or it is a real issue for everyone else

2:the copy paste but has reappeared somehow 

3: 
![Screenshot_2022-11-17-14-11-40-395.jpeg](https://user-images.githubusercontent.com/76000535/202398176-2bfaad44-aced-4e97-97c1-4b89f5328fd9.jpeg)

I'm not sure how do I close this box? Is it removed?

**Comment by spck-io** [comment]
Thanks for the bug report. Sorry for the late reply, my excuse is that I have less time now to work on this project due to family matters. I believe 1. is fixed, 2. if not fixed can you provide additional info? 3. the behavior has been changed so that clicking on the icon in the side navigation bar twice will minimize the sidebar.
