### ISSUE TITLE
Bug: unicode characters rendering (android)

### ISSUE THREAD

**Issue by jchwenger** [spckio/spck-issues#583]
Hi there,

I'm encountering a rendering issue on Android 9.
Build 7.0.4.0
Chrome 108

This happens when I work with a file having IPA characters:

![Screenshot_20230103-134452_Spck Editor](https://user-images.githubusercontent.com/34098722/210360503-637f9b08-a359-4a40-80c6-e6feac8280df.jpg)

I was using the default font (Noto), and also tried Ubuntu and Nova.

I'm wondering if that's an issue with the editor or something else. Any ideas?

If you want to test it on your end [here are files with IPA characters](https://github.com/jchwenger/wordhoard/tree/master/English/ipa), that you can clone easily.

Thanks a lot in advance!

**Comment by spck-io** [comment]
This is a font issue as none of the fonts used provide the glyphs for IPA characters (only basic Latin + extended latin). Since the glyphs are missing, it will default to the system fonts available on your Android device. It appears that the default fonts on your phone also do not include glyphs for IPA characters which is causing the blank characters. I can look for some font to be included that includes this set of glyphs, or maybe if possible try to install some monospace font with these glyphs on your system.

<img width="376" alt="Screenshot 2023-01-03 at 9 24 30 PM" src="https://user-images.githubusercontent.com/42258400/210473195-34cab46f-1510-4a17-b3a9-edcb068ccd01.png">

**Comment by jchwenger** [comment]
Ah, great, thanks for the info! I am finding the install of additional fonts on Android 9 remarkably difficult, and so I guess the option of a font with all unicode characters within the editor would appeal to me, but at least I know where to look for a solution, thanks!

**Comment by spck-io** [comment]
Update: in release 7.0.5.2 (soon-to-be released), added support for IPA characters in the default font (NotoMono).

**Comment by jchwenger** [comment]
Amazing, thank you!
