### ISSUE TITLE
iOS 17 App crashes MEGAULTRABUG

### ISSUE THREAD

**Issue by ghost** [spckio/spck-issues#651]
- iPad Pro 12.9
- iOS 17.0
- SPCK latest version AppStore 

BUG: 
Whenever you tap any dropdown menu item (for ex. in app settings page > choose font etc.) the editor crashing and closing window. So you can’t change those settings. 

Also, it would be super useful to have file tabs, so you can edit multiple files simultaneously.

**Comment by spck-io** [comment]
Letting you know I'm actively working on this. I have installed the latest Simulator (iOS 17.0) for iPhone 15 and have also tested on a physical device and have not ran into this issue. Maybe this issue is the result of using an older SDK to compile the application and it's been fixed in the newer XCode version. I have been trying to get a release out in the App store for some time now, and was on the point of giving up. I will make another push for the release to be published.

**Comment by mrazmilan** [comment]
I'm also facing this issue (iOS Build 2.2.3, iOS version 17.0.3). I tried re-installing the app and restarting the phone, but that did not help.
I've been having this issue since I updated to iOS 17.
