### ISSUE TITLE
Not able to cut and paste

### ISSUE THREAD

**Issue by leovoon** [spckio/spck-issues#73]
Paste nothing, file nor directory

**Comment by Doublepicebs** [comment]
Happens with me, but the popup doesn't even get shown

**Comment by spck-io** [comment]
Can you provide more details? I’m not able to replicate this.

**Comment by c5c86a** [comment]
Copying from spck and pasting to spck works fine but only from the app keyboard.

In order to copy from another app like a browser and paste to spck, I had to keep the setting "extra keyboard" enabled.

Also enablimg the "amoled display" setting in my Samsumg A40 helps, otherwise half my long press attempt yo paste would do nothing.

I wish I could just use my android keyboard at spck
