### ISSUE TITLE
IME Keyboard behaving funny on Android 4.4 - ?

### ISSUE THREAD

**Issue by spck-io** [spckio/spck-issues#9]
If you are having issues with the Android delete key not working properly or duplicating of text please let me know here. 
Please include:
- Android version
- phone model
- virtual Keyboard used
- Chrome version on phone

I think switching to another Keyboard should resolve the issue (i.e. Hacker Keyboard). Currently believe there may be a solution out there for this. And the problem only appears to only affect some versions of Google Keyboard/Android so far.

UPDATE: I tested and found some text duplication problems when deleting on Android 5, Gboard, Chrome 39. Problems however went away after updating Chrome to the latest version.

**Comment by egst** [comment]
Hey, just wanted to report an issue with my keyboard.

Phone: Huawei P20 Lite
Android: 8.0.0
Keyboards tested:
* Swiftkey: OK
* Chrooma Keyboard: Problem
The problem is: On every key entry (including backspace), the last word is repeated.

I'm OK with switching the keyboard, but it would be nice to use the one I'm used to.

**Comment by spck-io** [comment]
I have forked ace editor and have fixed this issue. If you are still having problems past version 0.6.0 of the editor, please let me know here.
